export {default as Home } from './home/Home';
export {default as Navbar } from './navbar/Navbar';
export {default as Login } from './login/Login';
export {default as SignupSuccess } from './signup_success/SignupSuccess';
export {default as ProfilPage } from './profilPage/ProfilPage';
export {default as InfoSection } from './profilPage/InfoSection';
export {default as HomeLogged } from './homeLogged/HomeLogged';
export {default as AddPost } from './addPost/AddPost';
export {default as Post} from './post/Post';
export {default as FriendsPage} from './friendsPage/FriendsPage';
export {default as FriendWidget} from './friendWidget/FriendWidget';